// Generated by gencpp from file asl_turtlebot/DetectedObject.msg
// DO NOT EDIT!


#ifndef ASL_TURTLEBOT_MESSAGE_DETECTEDOBJECT_H
#define ASL_TURTLEBOT_MESSAGE_DETECTEDOBJECT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace asl_turtlebot
{
template <class ContainerAllocator>
struct DetectedObject_
{
  typedef DetectedObject_<ContainerAllocator> Type;

  DetectedObject_()
    : id(0)
    , name()
    , confidence(0.0)
    , distance(0.0)
    , thetaleft(0.0)
    , thetaright(0.0)
    , corners()  {
    }
  DetectedObject_(const ContainerAllocator& _alloc)
    : id(0)
    , name(_alloc)
    , confidence(0.0)
    , distance(0.0)
    , thetaleft(0.0)
    , thetaright(0.0)
    , corners(_alloc)  {
  (void)_alloc;
    }



   typedef uint32_t _id_type;
  _id_type id;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef double _confidence_type;
  _confidence_type confidence;

   typedef double _distance_type;
  _distance_type distance;

   typedef double _thetaleft_type;
  _thetaleft_type thetaleft;

   typedef double _thetaright_type;
  _thetaright_type thetaright;

   typedef std::vector<double, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<double>> _corners_type;
  _corners_type corners;





  typedef boost::shared_ptr< ::asl_turtlebot::DetectedObject_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::asl_turtlebot::DetectedObject_<ContainerAllocator> const> ConstPtr;

}; // struct DetectedObject_

typedef ::asl_turtlebot::DetectedObject_<std::allocator<void> > DetectedObject;

typedef boost::shared_ptr< ::asl_turtlebot::DetectedObject > DetectedObjectPtr;
typedef boost::shared_ptr< ::asl_turtlebot::DetectedObject const> DetectedObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::asl_turtlebot::DetectedObject_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::asl_turtlebot::DetectedObject_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::asl_turtlebot::DetectedObject_<ContainerAllocator1> & lhs, const ::asl_turtlebot::DetectedObject_<ContainerAllocator2> & rhs)
{
  return lhs.id == rhs.id &&
    lhs.name == rhs.name &&
    lhs.confidence == rhs.confidence &&
    lhs.distance == rhs.distance &&
    lhs.thetaleft == rhs.thetaleft &&
    lhs.thetaright == rhs.thetaright &&
    lhs.corners == rhs.corners;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::asl_turtlebot::DetectedObject_<ContainerAllocator1> & lhs, const ::asl_turtlebot::DetectedObject_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace asl_turtlebot

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::asl_turtlebot::DetectedObject_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::asl_turtlebot::DetectedObject_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asl_turtlebot::DetectedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::asl_turtlebot::DetectedObject_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asl_turtlebot::DetectedObject_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::asl_turtlebot::DetectedObject_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::asl_turtlebot::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2650e98dd260a5b8590eced757507d05";
  }

  static const char* value(const ::asl_turtlebot::DetectedObject_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2650e98dd260a5b8ULL;
  static const uint64_t static_value2 = 0x590eced757507d05ULL;
};

template<class ContainerAllocator>
struct DataType< ::asl_turtlebot::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "asl_turtlebot/DetectedObject";
  }

  static const char* value(const ::asl_turtlebot::DetectedObject_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::asl_turtlebot::DetectedObject_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 id\n"
"string name\n"
"float64 confidence\n"
"float64 distance\n"
"float64 thetaleft\n"
"float64 thetaright\n"
"float64[] corners\n"
;
  }

  static const char* value(const ::asl_turtlebot::DetectedObject_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::asl_turtlebot::DetectedObject_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.id);
      stream.next(m.name);
      stream.next(m.confidence);
      stream.next(m.distance);
      stream.next(m.thetaleft);
      stream.next(m.thetaright);
      stream.next(m.corners);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectedObject_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::asl_turtlebot::DetectedObject_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::asl_turtlebot::DetectedObject_<ContainerAllocator>& v)
  {
    s << indent << "id: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.id);
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "confidence: ";
    Printer<double>::stream(s, indent + "  ", v.confidence);
    s << indent << "distance: ";
    Printer<double>::stream(s, indent + "  ", v.distance);
    s << indent << "thetaleft: ";
    Printer<double>::stream(s, indent + "  ", v.thetaleft);
    s << indent << "thetaright: ";
    Printer<double>::stream(s, indent + "  ", v.thetaright);
    s << indent << "corners[]" << std::endl;
    for (size_t i = 0; i < v.corners.size(); ++i)
    {
      s << indent << "  corners[" << i << "]: ";
      Printer<double>::stream(s, indent + "  ", v.corners[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ASL_TURTLEBOT_MESSAGE_DETECTEDOBJECT_H
